# Generated by Django 6.0.8 on 2026-08-10 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient'),
        ('doctors', '0002_alter_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor'),
        ),
    ]
