# Generated by Django 6.0.8 on 2026-08-11 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_alter_doctor_consultation_fee_and_more'),
        ('patients', '0002_alter_patient_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('room_type', models.CharField(choices=[('general', 'General Ward'), ('semi_private', 'Semi Private'), ('private', 'Private'), ('icu', 'ICU')], default='general', max_length=20)),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_discharge', models.DateField(blank=True, null=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('cancelled', 'Cancelled')], default='admitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='doctors.doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='admissions.room')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
    ]
