import { DisasterType, type SurvivalGuide } from '../types';

export const SURVIVAL_GUIDES: SurvivalGuide[] = [
  // ── Earthquake ──────────────────────────────────────────────
  {
    id: 'earthquake-survival',
    disasterType: DisasterType.EARTHQUAKE,
    title: 'Earthquake Survival Guide',
    description: 'Essential steps to stay safe before, during, and after an earthquake.',
    icon: '🏚️',
    beforeSteps: [
      { order: 1, title: 'Secure heavy furniture', description: 'Anchor bookshelves, cabinets, and appliances to walls. Use earthquake straps or brackets.', priority: 'high', icon: '🔩' },
      { order: 2, title: 'Create an emergency kit', description: 'Pack water (4L/person/day for 3 days), non-perishable food, flashlight, batteries, first aid, whistle, dust masks, and important documents in a waterproof bag.', priority: 'critical', icon: '🎒' },
      { order: 3, title: 'Identify safe spots', description: 'Locate sturdy desks, tables, or interior walls away from windows, mirrors, and heavy objects in every room.', priority: 'high', icon: '🔍' },
      { order: 4, title: 'Plan evacuation routes', description: 'Map out two exit routes from each room and your building. Practice the routes with your family.', priority: 'high', icon: '🗺️' },
      { order: 5, title: 'Turn off utilities', description: 'Know where gas, water, and electric shutoffs are located. Keep a wrench accessible.', priority: 'medium', icon: '🔧' },
      { order: 6, title: 'Reinforce your structure', description: 'If building or renovating, ensure your home meets earthquake-resistant building codes.', priority: 'medium', icon: '🏗️' },
    ],
    duringSteps: [
      { order: 1, title: 'Drop, Cover, Hold On', description: 'Get on the ground, take cover under a sturdy table or desk, and hold on until shaking stops.', priority: 'critical', icon: '🫢' },
      { order: 2, title: 'Stay indoors', description: 'Do not run outside during shaking. Most injuries occur when people try to move during the earthquake.', priority: 'critical', icon: '🏠' },
      { order: 3, title: 'Move away from windows', description: 'If not near a table, crouch against an interior wall and protect your head and neck with your arms.', priority: 'high', icon: '🪟' },
      { order: 4, title: 'If outdoors, stay open', description: 'Move to an open area away from buildings, trees, power lines, and poles.', priority: 'high', icon: '🌳' },
      { order: 5, title: 'If driving, pull over', description: 'Stop the car in an open area. Avoid bridges, overpasses, and power lines. Stay inside with seatbelt on.', priority: 'medium', icon: '🚗' },
      { order: 6, title: 'Expect aftershocks', description: 'After the main shaking stops, be prepared for aftershocks. They can be strong enough to cause additional damage.', priority: 'high', icon: '⚠️' },
    ],
    afterSteps: [
      { order: 1, title: 'Check for injuries', description: 'Provide first aid to yourself and others. Do not move seriously injured people unless they are in immediate danger.', priority: 'critical', icon: '🏥' },
      { order: 2, title: 'Check for gas leaks', description: 'If you smell gas or hear a hissing sound, open windows, leave the building, and call 911 from outside.', priority: 'critical', icon: '💨' },
      { order: 3, title: 'Inspect your home', description: 'Check for structural damage. If your home is severely damaged, evacuate and do not re-enter until inspected.', priority: 'high', icon: '🔍' },
      { order: 4, title: 'Stay informed', description: 'Listen to emergency broadcasts for official information and instructions.', priority: 'high', icon: '📻' },
      { order: 5, title: 'Avoid damaged buildings', description: 'Stay out of buildings that appear damaged. Aftershocks can cause collapse of weakened structures.', priority: 'high', icon: '🚧' },
      { order: 6, title: 'Use text, not calls', description: 'Keep phone calls brief. Use text messages or social media to communicate your status.', priority: 'medium', icon: '📱' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day for 3 days', essential: true },
      { item: 'Non-perishable food', quantity: '3-day supply', essential: true },
      { item: 'Flashlight', quantity: '1 per person', essential: true },
      { item: 'Batteries', quantity: 'Extra set for each device', essential: true },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Whistle', quantity: '1 per person', essential: true },
      { item: 'Dust masks', quantity: '2 per person', essential: true },
      { item: 'Emergency radio', quantity: '1 (hand-crank preferred)', essential: true },
      { item: 'Cash', quantity: 'Small bills', essential: false },
      { item: 'Documents (copies)', quantity: 'Waterproof bag', essential: true },
      { item: 'Medications', quantity: '7-day supply', essential: true },
      { item: 'Blankets', quantity: '1 per person', essential: false },
    ],
    dos: [
      'Practice Drop, Cover, and Hold On regularly',
      'Keep an emergency kit in an accessible location',
      'Secure heavy furniture and appliances to walls',
      'Know how to shut off gas, water, and electricity',
      'Have a family communication plan',
      'Keep shoes and a flashlight by your bed',
    ],
    donts: [
      'Do not stand in a doorway (outdated advice)',
      'Do not run outside during shaking',
      'Do not light candles or matches (gas leak risk)',
      'Do not use elevators',
      'Do not panic or push others',
      'Do not ignore aftershocks',
    ],
  },

  // ── Flood ───────────────────────────────────────────────────
  {
    id: 'flood-survival',
    disasterType: DisasterType.FLOOD,
    title: 'Flood Survival Guide',
    description: 'How to prepare for, survive, and recover from flooding events.',
    icon: '🌊',
    beforeSteps: [
      { order: 1, title: 'Know your flood risk', description: 'Check if your area is in a flood zone using FEMA maps or local government resources.', priority: 'high', icon: '🗺️' },
      { order: 2, title: 'Prepare an emergency bag', description: 'Pack essentials: water, food, medications, flashlight, radio, waterproof bags for documents, phone charger, and change of clothes.', priority: 'critical', icon: '🎒' },
      { order: 3, title: 'Move valuables up', description: 'Relocate important items, electronics, and documents to higher floors or elevated areas.', priority: 'high', icon: '📦' },
      { order: 4, title: 'Know evacuation routes', description: 'Identify and practice evacuation routes to higher ground. Never walk or drive through floodwater.', priority: 'critical', icon: '🛤️' },
      { order: 5, title: 'Install sump pumps', description: 'Consider installing sump pumps with battery backup in your basement or lowest floor.', priority: 'medium', icon: '🔧' },
      { order: 6, title: 'Clear gutters and drains', description: 'Keep storm drains and gutters clear of debris to allow proper water flow.', priority: 'medium', icon: '🧹' },
    ],
    duringSteps: [
      { order: 1, title: 'Move to higher ground', description: 'Immediately move to higher floors or the highest point available. Do not wait for instructions if water is rising.', priority: 'critical', icon: '⬆️' },
      { order: 2, title: 'Avoid floodwater', description: 'Never walk, swim, or drive through floodwater. 6 inches of moving water can knock you down; 2 feet can sweep away a vehicle.', priority: 'critical', icon: '🚫' },
      { order: 3, title: 'Turn off electricity', description: 'If safe to do so, switch off main power breakers. Do not touch electrical equipment if wet.', priority: 'high', icon: '⚡' },
      { order: 4, title: 'Stay off bridges', description: 'Fast-moving water can wash away bridge foundations. Never cross a bridge over fast-flowing water.', priority: 'critical', icon: '🌉' },
      { order: 5, title: 'Listen to alerts', description: 'Monitor emergency broadcasts and weather radio for updates and evacuation orders.', priority: 'high', icon: '📻' },
      { order: 6, title: 'If trapped, signal for help', description: 'If trapped in a building, go to the highest level. Signal rescuers with a flashlight or by calling 911.', priority: 'critical', icon: '🔦' },
    ],
    afterSteps: [
      { order: 1, title: 'Return only when safe', description: 'Do not return home until authorities confirm it is safe. Check for structural damage before entering.', priority: 'critical', icon: '✅' },
      { order: 2, title: 'Avoid contaminated water', description: 'Floodwater may contain sewage, chemicals, and debris. Avoid contact and wash thoroughly if exposed.', priority: 'high', icon: '☣️' },
      { order: 3, title: 'Document damage', description: 'Photograph all damage for insurance claims before cleaning or repairing.', priority: 'high', icon: '📸' },
      { order: 4, title: 'Clean and disinfect', description: 'Remove standing water, dry out areas completely, and disinfect all surfaces that contacted floodwater.', priority: 'high', icon: '🧹' },
      { order: 5, title: 'Check utilities', description: 'Have electricians, gas company, and other professionals inspect systems before turning them back on.', priority: 'critical', icon: '🔌' },
      { order: 6, title: 'Watch for mold', description: 'Mold can begin growing within 24-48 hours. Remove wet materials and use dehumidifiers.', priority: 'medium', icon: '🍄' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day for 3 days', essential: true },
      { item: 'Non-perishable food', quantity: '3-day supply', essential: true },
      { item: 'Flashlight', quantity: '1 per person', essential: true },
      { item: 'Batteries', quantity: 'Extra set', essential: true },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Waterproof bags', quantity: 'Several', essential: true },
      { item: 'Waterproof boots', quantity: '1 pair per person', essential: true },
      { item: 'Emergency radio', quantity: '1', essential: true },
      { item: 'Phone charger (battery)', quantity: '1', essential: true },
      { item: 'Important documents', quantity: 'Copies in waterproof bag', essential: true },
    ],
    dos: [
      'Move to higher ground immediately if flooding',
      'Stay off roads if water is above the curb',
      'Keep emergency supplies accessible',
      'Monitor emergency alerts continuously',
      'Follow official evacuation orders',
      'Turn off utilities if time permits',
    ],
    donts: [
      'Never walk or drive through floodwater',
      'Never cross bridges over fast-flowing water',
      'Do not touch downed power lines',
      'Do not return home until authorities say safe',
      'Do not use contaminated floodwater',
      'Do not ignore evacuation orders',
    ],
  },

  // ── Wildfire ────────────────────────────────────────────────
  {
    id: 'wildfire-survival',
    disasterType: DisasterType.WILDFIRE,
    title: 'Wildfire Survival Guide',
    description: 'How to prepare for, evacuate from, and recover after wildfires.',
    icon: '🔥',
    beforeSteps: [
      { order: 1, title: 'Create defensible space', description: 'Clear vegetation and debris within 30 feet of your home. Trim trees and remove dead brush.', priority: 'high', icon: '🌳' },
      { order: 2, title: 'Prepare your home', description: 'Use fire-resistant building materials, close attic vents, remove flammable items from decks, and keep gutters clean.', priority: 'high', icon: '🏠' },
      { order: 3, title: 'Pack a go-bag', description: 'Keep essentials ready: medications, documents, phone, charger, water, snacks, clothing, and valuables.', priority: 'critical', icon: '🎒' },
      { order: 4, title: 'Plan evacuation routes', description: 'Identify multiple escape routes from your neighborhood. Practice driving them.', priority: 'critical', icon: '🗺️' },
      { order: 5, title: 'Register for alerts', description: 'Sign up for local emergency notification systems and keep your phone charged.', priority: 'high', icon: '📱' },
      { order: 6, title: 'Photograph your property', description: 'Document your home and belongings for insurance purposes.', priority: 'medium', icon: '📸' },
    ],
    duringSteps: [
      { order: 1, title: 'Evacuate early', description: 'Leave when ordered or as soon as fire threatens. Do not wait to see flames. Roads become congested quickly.', priority: 'critical', icon: '🚗' },
      { order: 2, title: 'Close everything', description: 'Close all windows, doors, and vents. Move flammable furniture away from windows. Leave lights on for visibility.', priority: 'high', icon: '🚪' },
      { order: 3, title: 'Protect yourself from smoke', description: 'Use N95 masks or wet cloth over nose and mouth. Smoke can be more dangerous than flames.', priority: 'critical', icon: '😷' },
      { order: 4, title: 'If trapped, shelter in place', description: 'Go to a room with few windows. Fill bathtub and sinks with water. Seal doors with wet towels.', priority: 'critical', icon: '🛁' },
      { order: 5, title: 'Wear protective clothing', description: 'Long sleeves, long pants, boots, and wool are fire-resistant. Cover exposed skin.', priority: 'high', icon: '🧥' },
      { order: 6, title: 'Monitor conditions', description: 'Listen to emergency radio for fire movement and evacuation updates.', priority: 'high', icon: '📻' },
    ],
    afterSteps: [
      { order: 1, title: 'Wait for all-clear', description: 'Do not return until authorities confirm the area is safe. Embers can reignite hours later.', priority: 'critical', icon: '✅' },
      { order: 2, title: 'Watch for hotspots', description: 'Watch for smoldering debris, ash pits, and weakened trees. Wear boots and long pants.', priority: 'high', icon: '🔥' },
      { order: 3, title: 'Check for structural damage', description: 'Do not enter buildings that appear unstable. Check roofs before entering.', priority: 'critical', icon: '🔍' },
      { order: 4, title: 'Avoid downed power lines', description: 'Report downed lines to the utility company. Assume all downed lines are live.', priority: 'critical', icon: '⚡' },
      { order: 5, title: 'Document and report', description: 'Photograph damage for insurance. Report hazards to local authorities.', priority: 'high', icon: '📸' },
      { order: 6, title: 'Seek mental health support', description: 'Wildfires are traumatic. Contact disaster mental health services if needed.', priority: 'medium', icon: '💚' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day for 3 days', essential: true },
      { item: 'N95 masks', quantity: '2 per person', essential: true },
      { item: 'Flashlight', quantity: '1 per person', essential: true },
      { item: 'Go-bag', quantity: '1 per person (clothing, docs, meds)', essential: true },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Battery-powered radio', quantity: '1', essential: true },
      { item: 'Phone charger (battery)', quantity: '1', essential: true },
      { item: 'Fire extinguisher', quantity: '1 (ABC type)', essential: false },
    ],
    dos: [
      'Evacuate early when told to do so',
      'Create and maintain defensible space',
      'Keep emergency supplies in your vehicle',
      'Close all windows and vents before leaving',
      'Wear protective clothing when near fire',
      'Stay informed via emergency radio',
    ],
    donts: [
      'Do not wait until you see flames to evacuate',
      'Do not stay to protect property',
      'Do not ignore evacuation orders',
      'Do not use air conditioning during smoke',
      'Do not drive through smoke or flames',
      'Do not return until authorities say safe',
    ],
  },

  // ── Cyclone / Hurricane ─────────────────────────────────────
  {
    id: 'cyclone-survival',
    disasterType: DisasterType.CYCLONE,
    title: 'Cyclone & Hurricane Survival Guide',
    description: 'How to prepare for, endure, and recover from cyclones and hurricanes.',
    icon: '🌀',
    beforeSteps: [
      { order: 1, title: 'Board up windows', description: 'Use plywood or hurricane shutters to protect windows and glass doors from flying debris.', priority: 'high', icon: '🪟' },
      { order: 2, title: 'Stock supplies', description: 'Have at least 3-7 days of water (4L/person/day), canned food, medications, battery radio, flashlights, and cash.', priority: 'critical', icon: '📦' },
      { order: 3, title: 'Reinforce your home', description: 'Secure outdoor furniture, reinforce garage doors, and check roof integrity.', priority: 'high', icon: '🏠' },
      { order: 4, title: 'Fill your vehicle', description: 'Keep gas tank full and have emergency car kit. Evacuation may require long drives.', priority: 'high', icon: '⛽' },
      { order: 5, title: 'Prepare for power outages', description: 'Charge devices, stock batteries, consider generator (outdoor use only), fill bathtubs with water.', priority: 'high', icon: '🔋' },
      { order: 6, title: 'Know your zone', description: 'Understand if you are in an evacuation zone. Know when to leave vs. shelter in place.', priority: 'critical', icon: '🗺️' },
    ],
    duringSteps: [
      { order: 1, title: 'Shelter in interior room', description: 'Stay in an interior room away from windows on the lowest floor (not basement if flooding risk).', priority: 'critical', icon: '🏠' },
      { order: 2, title: 'Stay away from glass', description: 'Winds can shatter windows. Cover yourself with mattress or heavy blankets if glass breaks.', priority: 'critical', icon: '🪟' },
      { order: 3, title: 'Do not go outside', description: 'The eye of the storm may seem calm, but dangerous winds return suddenly from the opposite direction.', priority: 'critical', icon: '🚫' },
      { order: 4, title: 'Monitor conditions', description: 'Keep emergency radio on for updates. Do not use candles due to fire risk.', priority: 'high', icon: '📻' },
      { order: 5, title: 'Avoid flood-prone areas', description: 'Move to highest floor if flooding occurs. Never drive through floodwater.', priority: 'high', icon: '🌊' },
      { order: 6, title: 'Prepare for tornadoes', description: 'Cyclones can spawn tornadoes. Be ready to move to the safest room.', priority: 'medium', icon: '🌪️' },
    ],
    afterSteps: [
      { order: 1, title: 'Wait for official all-clear', description: 'Do not leave shelter until authorities confirm it is safe.', priority: 'critical', icon: '✅' },
      { order: 2, title: 'Avoid downed power lines', description: 'Report downed lines. Assume all wires are live and dangerous.', priority: 'critical', icon: '⚡' },
      { order: 3, title: 'Watch for debris', description: 'Wear sturdy shoes and gloves. Debris can contain nails, glass, and hazardous materials.', priority: 'high', icon: '🔧' },
      { order: 4, title: 'Check for gas leaks', description: 'If you smell gas, leave immediately and call emergency services.', priority: 'critical', icon: '💨' },
      { order: 5, title: 'Document damage', description: 'Photograph everything for insurance. Do not begin permanent repairs until documented.', priority: 'high', icon: '📸' },
      { order: 6, title: 'Use clean water only', description: 'Do not use tap water until authorities confirm it is safe. Use bottled or boiled water.', priority: 'high', icon: '💧' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day for 7 days', essential: true },
      { item: 'Canned food', quantity: '7-day supply', essential: true },
      { item: 'Battery radio', quantity: '1', essential: true },
      { item: 'Flashlights', quantity: '2', essential: true },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Cash', quantity: 'Small bills', essential: true },
      { item: 'Important documents', quantity: 'Copies in waterproof bag', essential: true },
      { item: 'Medications', quantity: '7-day supply', essential: true },
    ],
    dos: [
      'Evacuate when ordered to do so',
      'Board up windows before the storm',
      'Fill your gas tank and charge devices',
      'Stay in interior room during storm',
      'Listen to emergency broadcasts',
      'Stock enough supplies for 7 days',
    ],
    donts: [
      'Do not stay in mobile homes during a storm',
      'Do not go outside during the storm eye',
      'Do not use candles for lighting',
      'Do not drive through flooded roads',
      'Do not return home until all-clear',
      'Do not ignore evacuation orders',
    ],
  },

  // ── Heatwave ────────────────────────────────────────────────
  {
    id: 'heatwave-survival',
    disasterType: DisasterType.HEATWAVE,
    title: 'Heatwave Survival Guide',
    description: 'How to protect yourself and others during extreme heat events.',
    icon: '☀️',
    beforeSteps: [
      { order: 1, title: 'Stock up on water', description: 'Have at least 4L of water per person per day. Consider electrolyte drinks for extended heat.', priority: 'critical', icon: '💧' },
      { order: 2, title: 'Prepare your home', description: 'Install reflective window coverings, ensure AC works properly, check insulation.', priority: 'high', icon: '🏠' },
      { order: 3, title: 'Plan cooling options', description: 'Identify cooling centers, public pools, libraries. Know where to go if AC fails.', priority: 'high', icon: '❄️' },
      { order: 4, title: 'Check on vulnerable people', description: 'Identify elderly, children, and chronically ill neighbors. Plan wellness checks.', priority: 'high', icon: '👥' },
      { order: 5, title: 'Dress appropriately', description: 'Have loose, light-colored, breathable clothing ready. Wide-brimmed hats and sunglasses.', priority: 'medium', icon: '👒' },
      { order: 6, title: 'Adjust your schedule', description: 'Plan outdoor activities for early morning or evening. Avoid midday sun (10am-4pm).', priority: 'medium', icon: '📅' },
    ],
    duringSteps: [
      { order: 1, title: 'Stay hydrated', description: 'Drink water every 15-20 minutes even if not thirsty. Avoid alcohol and caffeine.', priority: 'critical', icon: '💧' },
      { order: 2, title: 'Stay cool', description: 'Use air conditioning, fans, cold showers, or visit cooling centers. Spend time in air-conditioned spaces.', priority: 'critical', icon: '❄️' },
      { order: 3, title: 'Never leave anyone in a car', description: 'Cars heat up to deadly temperatures in minutes. Never leave children, elderly, or pets in parked vehicles.', priority: 'critical', icon: '🚗' },
      { order: 4, title: 'Limit outdoor activity', description: 'Avoid strenuous activities during peak heat. If you must be outside, take frequent breaks in shade.', priority: 'high', icon: '🌳' },
      { order: 5, title: 'Know heat illness signs', description: 'Watch for heavy sweating, weakness, dizziness, nausea, headache, and rapid pulse.', priority: 'high', icon: '🏥' },
      { order: 6, title: 'Use sunscreen', description: 'Apply SPF 30+ sunscreen and reapply every 2 hours. Sunburn reduces your body\'s ability to cool.', priority: 'medium', icon: '🧴' },
    ],
    afterSteps: [
      { order: 1, title: 'Continue hydration', description: 'Keep drinking water after the heat event ends. Recovery takes time.', priority: 'high', icon: '💧' },
      { order: 2, title: 'Check on others', description: 'Visit elderly and vulnerable neighbors. Heat illness can have delayed symptoms.', priority: 'high', icon: '👥' },
      { order: 3, title: 'Inspect for damage', description: 'Check plants, pets, and property for heat damage. Water gardens in cooler hours.', priority: 'medium', icon: '🔍' },
      { order: 4, title: 'Report heat-related illness', description: 'Seek medical attention for anyone showing signs of heatstroke: confusion, no sweating, high body temperature.', priority: 'critical', icon: '🏥' },
      { order: 5, title: 'Review and plan ahead', description: 'Assess what worked and what didn\'t. Prepare better for the next event.', priority: 'medium', icon: '📋' },
      { order: 6, title: 'Cool your home at night', description: 'Open windows at night if cooler outside. Close and shade windows during the day.', priority: 'medium', icon: '🌙' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day', essential: true },
      { item: 'Electrolyte packets', quantity: '6 per person', essential: true },
      { item: 'Sunscreen SPF 30+', quantity: '1 bottle', essential: true },
      { item: 'Cooling towels', quantity: '2 per person', essential: true },
      { item: 'Wide-brimmed hats', quantity: '1 per person', essential: false },
      { item: 'Portable fan (battery)', quantity: '1 per person', essential: false },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Medications', quantity: '7-day supply', essential: true },
    ],
    dos: [
      'Drink water frequently even if not thirsty',
      'Stay in air-conditioned spaces during peak heat',
      'Check on elderly and vulnerable neighbors',
      'Wear light, loose clothing',
      'Know the signs of heat exhaustion and heatstroke',
      'Keep pets hydrated and in shade',
    ],
    donts: [
      'Never leave children or pets in parked cars',
      'Do not drink alcohol or excessive caffeine',
      'Do not exercise during peak heat hours',
      'Do not ignore symptoms of heat illness',
      'Do not leave vulnerable people alone',
      'Do not use fans in extremely hot, humid conditions without AC',
    ],
  },

  // ── Landslide ───────────────────────────────────────────────
  {
    id: 'landslide-survival',
    disasterType: DisasterType.LANDSLIDE,
    title: 'Landslide Survival Guide',
    description: 'How to recognize, prepare for, and survive landslides and mudslides.',
    icon: '⛰️',
    beforeSteps: [
      { order: 1, title: 'Know the risk', description: 'Check if you live in a landslide-prone area. Steep slopes, areas with loose soil, and after heavy rain are highest risk.', priority: 'high', icon: '🗺️' },
      { order: 2, title: 'Watch for warning signs', description: 'Cracks in ground/walls, tilting trees/fences, unusual water flow, rumbling sounds, sudden water level changes in streams.', priority: 'critical', icon: '⚠️' },
      { order: 3, title: 'Prepare your home', description: 'Reinforce slopes with retaining walls, improve drainage, plant deep-rooted vegetation.', priority: 'high', icon: '🏠' },
      { order: 4, title: 'Plan evacuation', description: 'Know evacuation routes to higher ground. Landslides move fast — you may have only seconds to react.', priority: 'critical', icon: '🛤️' },
      { order: 5, title: 'Emergency supplies', description: 'Keep a go-bag near exits with essentials. Landslides can block roads for days.', priority: 'high', icon: '🎒' },
      { order: 6, title: 'Monitor conditions', description: 'During heavy rain, stay alert. Listen for unusual sounds from hillsides.', priority: 'high', icon: '👂' },
    ],
    duringSteps: [
      { order: 1, title: 'Move to high ground', description: 'If you see or hear a landslide, move to higher ground immediately. Do not wait.', priority: 'critical', icon: '⬆️' },
      { order: 2, title: 'Move away from the slide path', description: 'Get sideways from the slide if possible. Landslides follow gravity downhill.', priority: 'critical', icon: '➡️' },
      { order: 3, title: 'If in a building, move to upper floors', description: 'Move away from windows toward the center of the building on upper floors.', priority: 'high', icon: '🏢' },
      { order: 4, title: 'Do not try to outrun in a vehicle', description: 'Landslides can engulf cars. Abandon the vehicle and move to higher ground on foot.', priority: 'critical', icon: '🚗' },
      { order: 5, title: 'Protect your head', description: 'Cover your head with your arms or any available object from flying debris.', priority: 'high', icon: '🫢' },
      { order: 6, title: 'Hold on if trapped', description: 'If caught in moving earth, try to grab something solid. Curl into a ball to protect vital organs.', priority: 'critical', icon: '🔒' },
    ],
    afterSteps: [
      { order: 1, title: 'Stay away from the slide area', description: 'Additional slides are likely. Do not enter the slide zone until authorities confirm it is safe.', priority: 'critical', icon: '🚫' },
      { order: 2, title: 'Check for injuries', description: 'Provide first aid. Do not move seriously injured people unless in immediate danger.', priority: 'high', icon: '🏥' },
      { order: 3, title: 'Watch for secondary slides', description: 'Remaining slopes may be unstable. Watch for new cracks or movement.', priority: 'critical', icon: '⚠️' },
      { order: 4, title: 'Check utilities', description: 'Look for broken gas lines, downed power lines, and water main breaks. Report to authorities.', priority: 'high', icon: '🔌' },
      { order: 5, title: 'Reconnect with family', description: 'Contact family and emergency contacts to report your status.', priority: 'high', icon: '📱' },
      { order: 6, title: 'Document damage', description: 'Photograph everything for insurance. Do not begin cleanup until documented.', priority: 'medium', icon: '📸' },
    ],
    emergencyKit: [
      { item: 'Water', quantity: '4L per person per day for 3 days', essential: true },
      { item: 'First aid kit', quantity: '1', essential: true },
      { item: 'Whistle', quantity: '1 per person', essential: true },
      { item: 'Helmet or hard hat', quantity: '1 per person', essential: false },
      { item: 'Sturdy boots', quantity: '1 pair per person', essential: true },
      { item: 'Flashlight', quantity: '1 per person', essential: true },
      { item: 'Phone charger', quantity: '1 (battery)', essential: true },
      { item: 'Documents', quantity: 'Copies in waterproof bag', essential: true },
    ],
    dos: [
      'Move to high ground if you see signs of a landslide',
      'Stay alert during and after heavy rainfall',
      'Evacuate immediately if authorities advise',
      'Watch for warning signs in slopes and hillsides',
      'Keep emergency supplies near exits',
      'Listen for unusual sounds from hillsides',
    ],
    donts: [
      'Do not stay in homes on steep slopes during heavy rain',
      'Do not try to outrun a landslide in a car',
      'Do not return to slide area until confirmed safe',
      'Do not ignore warning signs',
      'Do not build on steep slopes without engineering assessment',
      'Do not cross areas with flowing debris',
    ],
  },

  // ── First Aid ───────────────────────────────────────────────
  {
    id: 'first-aid-general',
    disasterType: DisasterType.EARTHQUAKE,
    title: 'General First Aid Guide',
    description: 'Essential first aid knowledge for any emergency or disaster situation.',
    icon: '🏥',
    beforeSteps: [
      { order: 1, title: 'Take a first aid course', description: 'Complete a certified first aid and CPR course. Refresh your skills every 2 years.', priority: 'critical', icon: '📚' },
      { order: 2, title: 'Stock a first aid kit', description: 'Bandages, gauze, antiseptic, tape, scissors, tweezers, gloves, CPR mask, pain relievers, tourniquet.', priority: 'critical', icon: '🧰' },
      { order: 3, title: 'Know your medical history', description: 'Keep a record of allergies, medications, and conditions. Store copies in your emergency kit.', priority: 'high', icon: '📋' },
      { order: 4, title: 'Learn emergency numbers', description: 'Know local emergency numbers: 911 (US), 112 (EU), local ambulance, poison control.', priority: 'high', icon: '📞' },
      { order: 5, title: 'Identify medical contacts', description: 'Know the nearest hospital, urgent care, and your doctor\'s after-hours number.', priority: 'medium', icon: '🏥' },
      { order: 6, title: 'Practice scenarios', description: 'Practice first aid scenarios with your family: CPR, choking, bleeding control, burns.', priority: 'medium', icon: '🏃' },
    ],
    duringSteps: [
      { order: 1, title: 'Assess the scene', description: 'Ensure the area is safe before approaching. Do not become a victim yourself.', priority: 'critical', icon: '🔍' },
      { order: 2, title: 'Call for help', description: 'Call emergency services immediately. Delegate someone to call if you are providing care.', priority: 'critical', icon: '📞' },
      { order: 3, title: 'Control severe bleeding', description: 'Apply firm, direct pressure with a clean cloth. Do not remove the cloth if it soaks through. Apply a tourniquet if trained.', priority: 'critical', icon: '🩸' },
      { order: 4, title: 'Perform CPR if needed', description: 'Start chest compressions (100-120/min) if person is unresponsive and not breathing normally. Use AED if available.', priority: 'critical', icon: '❤️' },
      { order: 5, title: 'Treat shock', description: 'Lay person flat, elevate legs, keep warm and calm. Do not give food or drink.', priority: 'high', icon: '😰' },
      { order: 6, title: 'Immobilize suspected fractures', description: 'Do not move the injured area. Use splints if available. Wait for professional help.', priority: 'high', icon: '🦴' },
    ],
    afterSteps: [
      { order: 1, title: 'Monitor the patient', description: 'Watch for changes in consciousness, breathing, and vital signs. Update emergency responders.', priority: 'high', icon: '👁️' },
      { order: 2, title: 'Follow up on wounds', description: 'Clean and re-bandage wounds regularly. Watch for signs of infection: redness, swelling, warmth, pus.', priority: 'high', icon: '🩹' },
      { order: 3, title: 'Seek professional care', description: 'Visit a doctor for any serious injury. Delayed symptoms can indicate hidden injuries.', priority: 'high', icon: '🏥' },
      { order: 4, title: 'Restock supplies', description: 'Replace any used first aid items immediately.', priority: 'medium', icon: '📦' },
      { order: 5, title: 'Update your knowledge', description: 'Review first aid procedures after using them. Practice areas where you felt unsure.', priority: 'medium', icon: '📖' },
      { order: 6, title: 'Document injuries', description: 'Record injuries, treatments given, and timeline for medical and insurance purposes.', priority: 'medium', icon: '📝' },
    ],
    emergencyKit: [
      { item: 'Adhesive bandages', quantity: 'Assorted sizes (20+)', essential: true },
      { item: 'Sterile gauze pads', quantity: '10 (4x4 inch)', essential: true },
      { item: 'Adhesive tape', quantity: '1 roll', essential: true },
      { item: 'Elastic bandage', quantity: '2 (3 inch)', essential: true },
      { item: 'Antiseptic wipes', quantity: '20', essential: true },
      { item: 'Antibiotic ointment', quantity: '1 tube', essential: true },
      { item: 'Scissors', quantity: '1', essential: true },
      { item: 'Tweezers', quantity: '1', essential: true },
      { item: 'Disposable gloves', quantity: '4 pairs', essential: true },
      { item: 'CPR breathing barrier', quantity: '1', essential: true },
      { item: 'Tourniquet (CAT)', quantity: '1', essential: true },
      { item: 'Pain relievers', quantity: 'Ibuprofen & Acetaminophen', essential: true },
      { item: 'Instant cold packs', quantity: '2', essential: false },
      { item: 'Emergency blanket', quantity: '2', essential: true },
      { item: 'First aid manual', quantity: '1', essential: true },
    ],
    dos: [
      'Always ensure scene safety before helping',
      'Call emergency services for serious injuries',
      'Apply firm pressure to control bleeding',
      'Keep victims warm and calm',
      'Wear gloves when providing first aid',
      'Practice CPR and first aid regularly',
    ],
    donts: [
      'Do not move victims with suspected spinal injuries',
      'Do not remove objects embedded in wounds',
      'Do not apply tourniquets without training',
      'Do not give food or water to unconscious victims',
      'Do not ignore head or neck injuries',
      'Do not delay calling for professional help',
    ],
  },
];

export const getSurvivalGuide = (type: DisasterType): SurvivalGuide | undefined => {
  return SURVIVAL_GUIDES.find((guide) => guide.disasterType === type && guide.id !== 'first-aid-general');
};

export const getFirstAidGuide = (): SurvivalGuide | undefined => {
  return SURVIVAL_GUIDES.find((guide) => guide.id === 'first-aid-general');
};
