# Generated by Django 6.0.8 on 2026-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='MediCare Hospital', max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='$', max_length=10)),
                ('working_hours', models.CharField(blank=True, help_text='e.g. Mon-Sat, 9:00 AM - 6:00 PM', max_length=100)),
                ('footer_text', models.CharField(blank=True, max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital settings',
                'verbose_name_plural': 'Hospital settings',
            },
        ),
    ]
